#!/bin/sh

set -eu

HOOK_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(CDPATH= cd -- "$HOOK_DIR/.." && pwd)
. "$HOOK_DIR/versioning.sh"

MESSAGE_FILE=$1
version=$(read_version)
timestamp=$(date -u '+%Y-%m-%d-%H%M')
prefix="$version build $timestamp "
temporary=$(mktemp "${MESSAGE_FILE}.XXXXXX")
trap 'rm -f "$temporary"' EXIT HUP INT TERM

awk -v prefix="$prefix" '
BEGIN { subject_found = 0 }
{
    if (!subject_found && $0 !~ /^[[:space:]]*#/ && $0 != "") {
        sub(/^[0-9]+\.[0-9]\.[0-9] build [0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{4} /, "", $0)
        print prefix $0
        subject_found = 1
    } else {
        print $0
    }
}
' "$MESSAGE_FILE" > "$temporary"

mv "$temporary" "$MESSAGE_FILE"
trap - EXIT HUP INT TERM
