[package]
name = "linuxfs-squashfs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
linuxfs-core = { path = "../linuxfs-core" }
squashfs_reader = { version = "0.1.1", default-features = false, features = ["only_rust"] }

[lints]
workspace = true
