[package]
name = "linuxfs-preview"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "LinuxFSManager"
path = "src/main.rs"

[dependencies]
linuxfs-app = { path = "../linuxfs-app" }
linuxfs-core = { path = "../linuxfs-core" }
linuxfs-winfsp = { path = "../linuxfs-winfsp" }
slint = "1.13"

[target.'cfg(windows)'.dependencies]
rfd = "0.15"
winfsp = "0.13"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[lints]
workspace = true
