[package]
name = "linuxfs-config"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
linuxfs-core = { path = "../linuxfs-core" }
serde = { version = "1", features = ["derive"] }
toml = "0.9"
windows-sys = { version = "0.61", features = ["Win32_Storage_FileSystem"] }

[lints]
workspace = true
