[package]
name = "linuxfs-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "linuxfs"
path = "src/main.rs"

[dependencies]
linuxfs-core = { path = "../linuxfs-core" }
linuxfs-ext = { path = "../linuxfs-ext" }
linuxfs-storage = { path = "../linuxfs-storage" }

[lints]
workspace = true
