[package]
name = "linuxfs-winfsp"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
linuxfs-core = { path = "../linuxfs-core" }

[lints]
workspace = true

[target.'cfg(windows)'.dependencies]
winfsp = { version = "0.13", default-features = false, features = ["delayload", "system"] }
winfsp-sys = { version = "0.12", default-features = false }
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_System_IO", "Win32_System_LibraryLoader", "Win32_System_Registry", "Win32_System_Services"] }

[target.'cfg(windows)'.build-dependencies]
winfsp = { version = "0.13", default-features = false, features = ["delayload", "system"] }
[dev-dependencies]
linuxfs-ext = { path = "../linuxfs-ext" }
linuxfs-storage = { path = "../linuxfs-storage" }
