#!/usr/bin/env bash
set -euo pipefail

output_dir="$1"
command -v mksquashfs >/dev/null || { echo "mksquashfs is required in WSL" >&2; exit 2; }
command -v mkfs.xfs >/dev/null || { echo "mkfs.xfs is required in WSL; install xfsprogs" >&2; exit 2; }

mkdir -p "$output_dir"
source_dir="$(mktemp -d)"
trap 'rm -rf "$source_dir"' EXIT
mkdir -p "$source_dir/root/etc" "$source_dir/root/docs"
printf '%s\n' 'LinuxFS Manager disposable SquashFS fixture.' > "$source_dir/root/README.txt"
printf '%s\n' 'This fixture contains no private or source-disk data.' > "$source_dir/root/etc/fixture.conf"
printf '%s\n' 'Generated by tools/generate-linux-fixtures.ps1.' > "$source_dir/root/docs/README.txt"

mksquashfs "$source_dir/root" "$output_dir/squashfs.img" -noappend -comp xz -quiet
truncate -s 512M "$output_dir/xfs.img"
mkfs.xfs -f -m crc=1,finobt=1 "$output_dir/xfs.img" >/dev/null

stat -c 'squashfs.img %s bytes' "$output_dir/squashfs.img"
stat -c 'xfs.img %s bytes (sparse)' "$output_dir/xfs.img"
