[package]
name = "linuxfs-app"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
linuxfs-core = { path = "../linuxfs-core" }
linuxfs-backends = { path = "../linuxfs-backends" }
linuxfs-config = { path = "../linuxfs-config" }
linuxfs-ext = { path = "../linuxfs-ext" }
linuxfs-storage = { path = "../linuxfs-storage" }
linuxfs-windows = { path = "../linuxfs-windows" }
linuxfs-winfsp = { path = "../linuxfs-winfsp" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

[lints]
workspace = true
